apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: gitpods-try
  labels:
    app: storage
spec:
  type: NodePort
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
