workspace:
  base: /go
  path: src/github.com/gitpods/gitpods

pipeline:
  test:
    image: golang:1.8
    commands:
      - go get -v -t ./...
      - go test -v ./...

  api:
    group: build
    image: golang:1.8
    commands:
      - go install -v ./cmd/api

  gitpods:
    group: build
    image: golang:1.8
    commands:
      - go install -v ./cmd/gitpods

  ui:
    group: build
    image: golang:1.8
    commands:
      - go install -v ./cmd/ui

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
