workspace:
  base: /go
  path: src/github.com/gitpods/gitpods

pipeline:
  webpack:
    group: dependencies
    image: kkarczmarczyk/node-yarn
    commands:
      - yarn install
      - ./node_modules/.bin/webpack

  test:
    image: golang:1.8
    commands:
      - go test -v ./...

  api:
    group: build
    image: golang:1.8
    commands:
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/api/api ./cmd/api

  gitpods:
    group: build
    image: golang:1.8
    commands:
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/gitpods/gitpods ./cmd/gitpods

  ui:
    group: build
    image: golang:1.8
    commands:
      - go get -u github.com/gobuffalo/packr/...
      - packr
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/ui/ui ./cmd/ui

  docker-api:
    group: docker
    image: plugins/docker
    repo: gitpods/api
    dockerfile: ./cmd/api/Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  docker-ui:
    group: docker
    image: plugins/docker
    repo: gitpods/ui
    dockerfile: cmd/ui/Dockerfile
    context: ./cmd/ui
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  kubernetes-api:
    group: deployment
    image: vallard/drone-kube
    namespace: gitpods
    template: deployment/kubernetes/api/deployment.yml
    secrets: [ KUBE_SERVER, KUBE_CA, KUBE_TOKEN ]
    when:
      branch: master
      event: push

  kubernetes-ui:
    group: deployment
    image: vallard/drone-kube
    namespace: gitpods
    template: deployment/kubernetes/ui/deployment.yml
    secrets: [ KUBE_SERVER, KUBE_CA, KUBE_TOKEN ]
    when:
      branch: master
      event: push

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
