workspace:
  base: /go
  path: src/github.com/gitpods/gitpods

pipeline:
  test:
    image: golang:1.8
    commands:
      - go get -v -t ./...
      - go test -v ./...

  api:
    group: build
    image: golang:1.8
    commands:
      - go install -v ./cmd/api

  stratus:
    group: build
    image: golang:1.8
    commands:
      - go install -v ./cmd/stratus

  ui:
    group: build
    image: golang:1.8
    commands:
      - go install -v ./cmd/ui

  notify:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
    when:
      status: [ success, failure ]
