version: '2'

services:
  ui:
    image: gitpods/ui
    restart: always
    ports:
      - 3010:3010
    environment:
    - GITPODS_ADDR=localhost:3010
    - GITPODS_ADDR_API=http://localhost:3000/api
    - GITPODS_ENV=production
    - GITPODS_LOGLEVEL=info

  api:
    image: gitpods/api
    restart: always
    depends_on:
    - ui
    ports:
      - 3020:3020
    environment:
    - GITPODS_ADDR=localhost:3020
    - GITPODS_ENV=production
    - GITPODS_LOGLEVEL=info
