apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: gitpods-try
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.6
        imagePullPolicy: "IfNotPresent"
        env:
        - name: PGUSER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        ports:
        - containerPort: 5432
