apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: gitpods-try
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
