apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: gitpods-try
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: gitpods/ui:latest
        env:
        - name: GITPODS_LISTEN_ADDR
          value: 0.0.0.0:3010
        - name: GITPODS_API_URL
          value: http://try.gitpods.io/api
        - name: GITPODS_LOG_LEVEL
          value: debug
        - name: GITPODS_LOG_JSON
          value: 'true'
        # This hash is not needed and only used to track which version is deployed when using :latest
        - name: HASH
          value: {{ build.commit }}
        ports:
        - containerPort: 3010
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
