apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: gitpods
  labels:
    app: ui
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
