apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: gitpods-try
  labels:
    app: ui
spec:
  type: ClusterIP
  selector:
    app: ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3010
