apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitpods
  namespace: gitpods
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - try.gitpods.io
    secretName: gitpods-tls
  rules:
  - host: try.gitpods.io
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 80
      - backend:
          serviceName: api
          servicePort: 80
        path: /api
      - backend:
          serviceName: api
          servicePort: 80
        path: /api/*
