apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: gitpods-try
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3020
